### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by froydnj** [mozilla/git-bz-moz#71]
Just pulled and now get:

```
Traceback (most recent call last):
  File "/home/froydnj/bin/git-bz", line 69, in <module>
    import bzauth
  File "/home/froydnj/src/git-bz-moz/bzauth.py", line 33, in <module>
    import requests
ImportError: No module named requests
```

I guess we need to say something about having https://pypi.python.org/pypi/requests installed?  (Things appear to work OK after I installed that...)

**Comment by amccreight** [comment]
Weird. I must have incidentally auto installed it for something else.

**Comment by indygreg** [comment]
We have the requests package vendored in version-control-tools. If you move git-bz-moz to version-control-tools, you can do some sys.path manipulation to automagically add it to the search path.

Also, please don't make requests optional because it contains improvements to TLS that make it not suck by default on Python <2.7.9. (You pretty much had to "opt in" to proper security because Python stdlib modules themselves weren't doing it for you. Even 2.7.9 isn't a magic bullet: requests still adjusts the connection settings to make security suck less.) tl;dr always use requests for HTTP requests because security.

**Comment by amccreight** [comment]
Don't worry, I'm not planning on touching this file. :)
