### ISSUE TITLE
git bz apply should get mozreview patch information from hg changeset

### ISSUE THREAD

**Issue by glandium** [mozilla/git-bz-moz#90]
When using git bz apply and the bug attachments are mozreview requests, the applied patches don't have the right authorship: the dates are wrong, and the author name is the author email (as in, git log shows the Author as `email <email>`)

**Comment by chenpighead** [comment]
cc @aethanyc

**Comment by chenpighead** [comment]
In the [PR](https://github.com/mozilla/git-bz-moz/pull/93), I only fixed the authorship issue.

As to the date issue, since raw diff's lack of authorship and patch creation time, we can only refer to the authorship and creation time from Bugzilla. I think that's the reason why the original implementation treat attachment uploader as the author, and attachment creation time as the patch creation time.

As can be seen in the [example](https://bugzilla.mozilla.org/rest/bug/1056516/attachment), only two possible time can be referred, `creation_time` or `last_change_time`. IMHO, `creation_time` makes more sense to me, so I'm not sure if we should treat the date/time issue as a bug.

**Comment by glandium** [comment]
mozreview requests have corresponding mercurial changesets. Those have full authorship information, including date.

**Comment by chenpighead** [comment]
I can't find a trivial way to get the corresponding mercurial changesets... :(
Maybe after [Bug 1346321](https://bugzilla.mozilla.org/show_bug.cgi?id=1346321) is fixed, we could get the corresponding mercurial changesets. Then, we can apply the full authorship information accordingly.

**Comment by amccreight** [comment]
I'll leave the issue open for the more specific request, in case somebody wants to figure out how to do that. #93 will at least improve the situation, and also applies to the case of diffs attached to Bugzilla that have no information.

**Comment by amccreight** [comment]
mozreview is no more.
